<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/9/18
 * Time: 14:10
 */
namespace app\admin\controller;

use think\Controller;

class Base extends Controller{

    public  function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

//        $admin=session('admin');
//        if(empty($admin)||!isset($admin)){
//            return $this->error('请先登录...','Login/login');
//        }
    }

//    public function _empty(){
//        return $this->fetch('empty');
//    }


}